name: earhquake_stock_managment
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  kartal: ^2.8.0
  lottie: ^2.2.0
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  syncfusion_flutter_datagrid_export: ^20.4.49-beta

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
